# Generated by Django 4.2.4 on 2023-08-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_alter_agentpublic_id_ag_pb_alter_candidature_id_cand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='id_chef_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscription.chefdepart'),
        ),
    ]
