# Generated by Django 4.2.4 on 2023-08-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_tache_id_chef_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleme',
            name='id_ag_pb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscription.agentpublic'),
        ),
        migrations.AddField(
            model_name='probleme',
            name='id_ag_pb_recept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemes_receptes', to='inscription.agentpublic'),
        ),
    ]
