# Generated by Django 4.2.4 on 2023-08-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_remove_probleme_id_ag_pb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plainte',
            name='lib_plainte',
        ),
        migrations.AddField(
            model_name='plainte',
            name='id_prob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscription.probleme'),
        ),
    ]
