# Generated by Django 4.2.4 on 2023-08-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_remove_plainte_lib_plainte_plainte_id_prob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='lib_cand',
            field=models.TextField(),
        ),
    ]
