# Generated by Django 4.2.4 on 2023-08-17 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0008_alter_candidature_lib_cand'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpublic',
            name='date_nais_ag_pb',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentpublic',
            name='id_cand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscription.candidature'),
        ),
        migrations.AlterField(
            model_name='agentpublic',
            name='date_nomination_ag_pb',
            field=models.DateField(),
        ),
    ]
