# Generated by Django 4.2.4 on 2023-08-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0009_agentpublic_date_nais_ag_pb_agentpublic_id_cand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentpublic',
            name='etat_ag_pb',
        ),
    ]
